-- TESTING EMPLOYEES PAYROLL MANAGEMENT SYSTEM
INSERT INTO EMP_DEPARTMENTS VALUES (1, 'HR');
INSERT INTO EMP_DEPARTMENTS VALUES (2, 'IT');


INSERT INTO employees
VALUES (101, 'Rahul', 2, 40000, 8000, 5000, SYSDATE);

INSERT INTO employees
VALUES (102, 'Anita', 1, 30000, 6000, 3000, SYSDATE);
INSERT INTO EMPLOYEES
VALUES(103,'AMAN', 2, 4000, 4758, 2400, SYSDATE);
BEGIN
    payroll_pkg.cal_salary(103, 'JAN-25');
END;
/

BEGIN
    payroll_pkg.SALARY_REPORT_DEPT(2);
END;
/

BEGIN
    SAL_AUDIT()
END;
/
SELECT * FROM EMP_SALARY;
SELECT * FROM EMP_DEPARTMENT;
SELECT * FROM EMPLOYEES;
