CREATE OR REPLACE FUNCTION CAL_GRADE(TOTAL_MARKS NUMBER)
    RETURN VARCHAR2 IS
        GRADE VARCHAR2(2);

BEGIN
    IF TOTAL_MARKS >= 90 AND TOTAL_MARKS <= 100 THEN 
        GRADE:='A';
    ELSIF TOTAL_MARKS >= 80 AND TOTAL_MARKS < 90 THEN
        GRADE :='B';
    ELSIF TOTAL_MARKS >= 70 AND TOTAL_MARKS < 80 THEN 
        GRADE :='C';
    ELSIF TOTAL_MARKS >= 60 AND TOTAL_MARKS < 70 THEN
        GRADE :='D';
    ELSIF TOTAL_MARKS >= 50 AND TOTAL_MARKS < 60 THEN
        GRADE :='E';
    ELSE 
        GRADE :='F';
    END IF;

    RETURN GRADE;
END;
/


