CREATE TABLE OERPS_STUDENTS( 
    ST_ID NUMBER,
    ST_NAME VARCHAR2(100),
    ST_DOB DATE,
    ST_PHONE VARCHAR2(10)
);

CREATE TABLE OERPS_SUBJECTS(
    SUB_ID NUMBER,
    SUB_NAME VARCHAR2(50)
    
);

CREATE TABLE OERPS_MARKS(
    MARK_ID NUMBER,
    STU_ID NUMBER,
    SUB_ID NUMBER,
    MARK_OBTAIN NUMBER,
    MARK_MAX NUMBER
);
CREATE TABLE OERPS_RESULTS(
    RESULT_ID NUMBER,
    STU_ID NUMBER,
    STU_GRADE VARCHAR2(2),
    TOTAL_MARKS NUMBER,
    PERCENT NUMBER,
    RES_STAT VARCHAR2(5),
    STU_RANK NUMBER
);
