INSERT INTO OERPS_STUDENTS VALUES (1, 'Amit', DATE '2002-05-10', '9876543210');
INSERT INTO OERPS_SUBJECTS VALUES (101, 'Maths');
INSERT INTO OERPS_SUBJECTS VALUES (102, 'Science');

INSERT INTO OERPS_MARKS VALUES (1, 1, 101, 80, 100);
INSERT INTO OERPS_MARKS VALUES (2, 1, 102, 70, 100);

SELECT * FROM OERPS_STUDENTS;
SELECT * FROM OERPS_SUBJECTS;
SELECT * FROM OERPS_MARKS;

BEGIN
    RES_PROCESS(1);
    RANK_GENERATOR;
END;
/

SELECT* FROM OERPS_RESULTS;

-- RESULT PUBLISH
SELECT s.st_name, r.total_marks, r.percent, r.stu_grade,
       r.res_stat, r.stu_rank
FROM oerps_students s
JOIN oerps_results r ON s.st_id = r.stu_id;
