CREATE OR REPLACE TRIGGER RSULT_UPDATION
AFTER INSERT OR UPDATE ON OERPS_MARKS
FOR EACH ROW
BEGIN
    DELETE FROM OERPS_RESULTS
    WHERE stu_id = :NEW.stu_id;

    RES_PROCESS(:NEW.stu_id);
END;
/
