-- CREATE OR REPLACE TRIGGER bank_update
-- AFTER INSERT 
-- ON bank_customers
-- FOR EACH ROW
-- BEGIN
--     INSERT INTO BANK_ACCOUNTS(acc_id,c_id, acc_num, balance)
--     VALUES(account_seq.nextval,:NEW.c_id, acc_num_seq.nextval,0);
    
-- END;
-- /

-- DROP TRIGGER bank_update;


CREATE OR REPLACE TRIGGER bank_trans
AFTER UPDATE
ON BANK_ACCOUNTS
FOR EACH ROW
BEGIN
    IF :OLD.BALANCE > :NEW.BALANCE THEN 
    INSERT INTO BANK_TRANSACTIONS(TRANSACTION_ID, ACC_ID, TRANS_TYPE,AMOUNT, REM_BAL)
    VALUES(TRANS_SEQ.nextval,:NEW.ACC_ID,'WITHDRAW',:OLD.BALANCE - :NEW.BALANCE,:NEW.BALANCE);
    END IF;
    IF :OLD.BALANCE < :NEW.BALANCE THEN 
    INSERT INTO BANK_TRANSACTIONS(TRANSACTION_ID, ACC_ID, TRANS_TYPE,AMOUNT, REM_BAL)
    VALUES(TRANS_SEQ.nextval,:NEW.ACC_ID,'DEPOSIT',:NEW.BALANCE-:OLD.BALANCE,:NEW.BALANCE);
    END IF;

END;
/
-- DROP TRIGGER BANK_TRANS;