CREATE OR REPLACE FUNCTION getbalance(get_bal IN NUMBER)
RETURN NUMBER IS
    CURR_BALANCE NUMBER(6);

BEGIN 
    SELECT BALANCE INTO CURR_BALANCE
    FROM BANK_ACCOUNTS
    WHERE acc_id = get_bal;

    RETURN CURR_BALANCE;
END;
/
