CREATE SEQUENCE customer_seq
START WITH 1
INCREMENT BY 1
NOCYCLE
CACHE 20;

CREATE SEQUENCE account_seq
START WITH 101
INCREMENT BY 1
NOCYCLE
CACHE 20;

CREATE SEQUENCE acc_num_seq
START WITH 1001
INCREMENT BY 1
NOCYCLE
CACHE 20;

CREATE SEQUENCE trans_seq
START WITH 1
INCREMENT BY 1
NOCYCLE
CACHE 20;